Add --long GNU options
* Fix version output

diff --git a/release/podc b/release/podc
--- a/release/podc
+++ b/release/podc
@@ -6,7 +6,7 @@
 #  /___/_/  /_/ |_\___/___(_)___/_//_/
 #  version: 1.4.0 | https://space.sh
 #
-# Node: /cmdline/
+# Node: /_cmdline/
 # Use podc as a standalone cmd line tool
 
 set -u  # Will not allow for unset variables being used.
@@ -23,31 +23,31 @@ PODC_CMDLINE()
 {
     local _SPACE_NAME="PODC_CMDLINE"
 
-    local _out_rest=""
-    local _out_h="false"
-    local _out_V="false"
+    local _out_arguments=""
+    local _out_h=
+    local _out_V=
     local _out_p="true"
 
     local _out_f=""
     local _out_o=""
     local _out_d=""
 
-    if ! _GETOPTS "h V" "f o d p" 0 1 "$@"; then
-        printf "Usage: pod [podname] [-f infile] [-o outfile] [-d srcdir] [-p true|false]\\n" >&2
+    if ! _GETOPTS "_out_h=-h,--help/ _out_V=-V,--version/ _out_f=-f,--file/* _out_o=-o,--outfile/* _out_d=-d,--dir/* _out_p=-p,--preprocess/true|false" 0 1 "$@"; then
+        printf "Usage: pod [podname] [-f|--file=] [-o|--outfile=] [-d|--dir=] [-p|--preprocess=true|false]\\n" >&2
         return 1
     fi
 
-    if [ "${_out_h}" = "true" ]; then
+    if [ -n "${_out_h}" ]; then
         USAGE
         return
     fi
 
-    if [ "${_out_V}" = "true" ]; then
+    if [ -n "${_out_V}" ]; then
         VERSION
         return
     fi
 
-    COMPILE_ENTRY "${_out_rest}" "${_out_f}" "${_out_o}" "${_out_d}" "${_out_p}"
+    COMPILE_ENTRY "${_out_arguments}" "${_out_f}" "${_out_o}" "${_out_d}" "${_out_p}"
 }
 
 USAGE()
@@ -94,10 +94,7 @@ _GETOPTS()
 {
     local _SPACE_NAME="_GETOPTS"
 
-    local simpleSwitches="${1}"
-    shift
-
-    local richSwitches="${1}"
+    local options="${1}"
     shift
 
     local minPositional="${1:-0}"
@@ -106,61 +103,101 @@ _GETOPTS()
     local maxPositional="${1:-0}"
     shift
 
-    _out_rest=""
-
-    local options=""
-    local option=
-    for option in ${richSwitches}; do
-        options="${options}${option}:"
-    done
-
+    _out_arguments=""
     local posCount="0"
+    local skipOptions="false"
     while [ "$#" -gt 0 ]; do
-        local flag="${1#-}"
-        if [ "${flag}" = "${1}" ]; then
-            # Non switch
+        local option=
+        local value=
+        local _out_VARNAME=
+        local _out_ARGUMENTS=
+
+        if [ "${skipOptions}" = "false" ] && [ "${1}" = "--" ]; then
+            skipOptions="true"
+            shift
+            continue
+        fi
+
+        if [ "${skipOptions}" = "false" ] && [ "${1#--}" != "${1}" ]; then # Check if it is a double dash GNU option
+            local l=
+            STRING_INDEXOF "=" "${1}" "l"
+            if [ "$?" -eq 0 ]; then
+                STRING_SUBSTR "${1}" 0 "${l}" "option"
+                STRING_SUBSTR "${1}" "$((l+1))" "" "value"
+            else
+                option="${1}"
+            fi
+            shift
+            # Fill _out_VARNAME and _out_ARGUMENTS
+            _GETOPTS_SWITCH "${options}" "${option}"
+            # Fall through to handle option
+        elif [ "${skipOptions}" = "false" ] && [ "${1#-}" != "${1}" ] && [ "${#1}" -gt 1 ]; then # Check single dash OG-style option
+            option="${1}"
+            shift
+            if [ "${#option}" -gt 2 ]; then
+                PRINT "Invalid option '${option}'" "error" 0
+                return 1
+            fi
+            # Fill _out_VARNAME and _out_ARGUMENTS
+            _GETOPTS_SWITCH "${options}" "${option}"
+            # Do we expect a value to the option? If so take it and shift it out
+            if [ -n "${_out_ARGUMENTS}" ]; then
+                if [ "$#" -gt 0 ]; then
+                    value="${1}"
+                    shift
+                fi
+            fi
+            # Fall through to handle option
+        else
+            # Positional args
             posCount="$((posCount+1))"
             if [ "${posCount}" -gt "${maxPositional}" ]; then
-                PRINT "Too many positional arguments, max ${maxPositional}" "error" 0
+                PRINT "Too many arguments. Max ${maxPositional} argument(s) allowed." "error" 0
                 return 1
             fi
-            _out_rest="${_out_rest}${_out_rest:+ }${1}"
-            shift
-            continue
-        fi
-        local flag2=
-        STRING_SUBSTR "${flag}" 0 1 "flag2"
-        if STRING_ITEM_INDEXOF "${simpleSwitches}" "${flag2}"; then
-            if [ "${#flag}" -gt 1 ]; then
-                PRINT "Invalid option: -${flag}" "error" 0
-                return 1
-            fi
-            eval "_out_${flag}=\"true\""
+            _out_arguments="${_out_arguments}${_out_arguments:+ }${1}"
             shift
             continue
         fi
 
-        local OPTIND=1
-        getopts ":${options}" "flag"
-        case "${flag}" in
-            \?)
-                PRINT "Unknown option ${1-}" "error" 0
-                return 1
-                ;;
-            :)
-                PRINT "Option -${OPTARG-} requires an argument" "error" 0
-                return 1
-                ;;
-            *)
-                STRING_ESCAPE "OPTARG"
-                eval "_out_${flag}=\"${OPTARG}\""
-                ;;
-        esac
-        shift $((OPTIND-1))
+        # Handle option argument
+        if [ -z "${_out_VARNAME}" ]; then
+            PRINT "Unrecognized option: '${option}'" "error" 0
+            return 1
+        fi
+
+        if [ -n "${_out_ARGUMENTS}" ] && [ -z "${value}" ]; then
+            # If we are expecting a option arguments but none was provided.
+            STRING_SUBST "_out_ARGUMENTS" " " ", " 1
+            PRINT "Option ${option} is expecting an argument like: ${_out_ARGUMENTS}" "error" 0
+            return 1
+        elif [ -z "${_out_ARGUMENTS}" ] && [ -z "${value}" ]; then
+            # This was a simple option without argument, increase counter of occurrences
+            eval "value=\"\$${_out_VARNAME}\""
+            if [ -z "${value}" ]; then
+                value=0
+            fi
+            value="$((value+1))"
+        elif [ "${_out_ARGUMENTS}" = "*" ] || STRING_ITEM_INDEXOF "${_out_ARGUMENTS}" "${value}"; then
+            # Value is OK, fall through
+            :
+        else
+            # Invalid argument
+            if [ -z "${_out_ARGUMENTS}" ]; then
+                PRINT "Option ${option} does not take any arguments" "error" 0
+            else
+                PRINT "Invalid ${option} argument '${value}'. Valid arguments are: ${_out_ARGUMENTS}" "error" 0
+            fi
+            return 1
+        fi
+
+        # Store arguments in variable
+        STRING_ESCAPE "value"
+        eval "${_out_VARNAME}=\"\${value}\""
     done
 
     if [ "${posCount}" -lt "${minPositional}" ]; then
-        PRINT "Too few positional arguments, min ${minPositional}" "error" 0
+        PRINT "Too few arguments provided. Minimum ${minPositional} argument(s) required." "error" 0
         return 1
     fi
 }
@@ -261,7 +298,44 @@ COMPILE_ENTRY()
 VERSION()
 {
     local _SPACE_NAME="VERSION"
-    printf "%s\\n" "Simplenetes pod compiler version 0.1 for api: 1.0.0-beta1"
+    printf "%s\\n%s\\n" "podc 0.3.0" "apiVersion 1.0.0-beta1"
+}
+
+_GETOPTS_SWITCH()
+{
+    local _SPACE_NAME="_GETOPTS_SWITCH"
+
+    local options="${1}"
+    shift
+
+    local option="${1}"
+    shift
+
+    local varname=
+    local arguments=
+
+    local count=0
+    local index=0
+    STRING_ITEM_COUNT "${options}" "count"
+    while [ "${index}" -lt "${count}" ]; do
+        local item=
+        STRING_ITEM_GET "${options}" ${index} "item"
+        varname="${item%%=*}"
+        arguments="${item#*/}"
+        local allSwitches="${item#*=}"
+        allSwitches="${allSwitches%%/*}"
+        STRING_SUBST "allSwitches" "," " " 1
+        if STRING_ITEM_INDEXOF "${allSwitches}" "${option}"; then
+            STRING_SUBST "arguments" "|" " " 1
+            _out_VARNAME="${varname}"
+            _out_ARGUMENTS="${arguments}"
+            return 0
+        fi
+        index=$((index+1))
+    done
+
+    # No such option found
+    return 1
 }
 
 PRINT()
@@ -789,6 +863,114 @@ FILE_REALPATH()
     printf "%s\\n" "${file}"
 }
 
+STRING_SUBST()
+{
+    local _SPACE_NAME="STRING_SUBST"
+
+    local __varname="${1}"
+    local __rstring=
+    eval "__rstring=\"\${$1}\""
+    shift
+
+    local __subst="${1}"
+    shift
+
+    local __replace="${1}"
+    shift
+
+    local __global="${1:-0}"
+    shift $(( $# > 0 ? 1 : 0 ))
+
+    local __lstring=
+    local __string=""
+    while true; do
+        __lstring="${__rstring%%${__subst}*}"
+        if [ "${__lstring}" = "${__rstring}" ]; then
+            __string="${__string}${__rstring}"
+            break
+        fi
+        __string="${__string}${__lstring}${__replace}"
+        __rstring="${__rstring#*${__subst}}"
+        if [ "${__global}" -ne 1 ]; then
+            __string="${__string}${__rstring}"
+            break
+        fi
+    done
+    eval "${__varname}=\"\${__string}\""
+}
+
+STRING_ITEM_INDEXOF()
+{
+    local _SPACE_NAME="STRING_ITEM_INDEXOF"
+
+    local __s="${1}"
+    shift
+
+    local __item="${1}"
+    shift
+
+    local __outvar="${1-}"
+    shift $(( $# > 0 ? 1 : 0 ))
+
+    local __item2=
+    local __count=0
+    for __item2 in ${__s}; do
+        if [ "${__item}" = "${__item2}" ]; then
+            if [ -n "${__outvar}" ]; then
+                eval "${__outvar}=\"\${__count}\""
+            fi
+            return 0
+        fi
+        __count=$((__count+1))
+    done
+    if [ -n "${__outvar}" ]; then
+        eval "${__outvar}=\"-1\""
+    fi
+    return 1
+}
+
+STRING_ITEM_GET()
+{
+    local _SPACE_NAME="STRING_ITEM_GET"
+
+    local __s="${1}"
+    shift
+
+    local __index="${1}"
+    shift
+
+    local __outvar="${1}"
+    shift
+
+    local __item=
+    local __count=0
+    for __item in ${__s}; do
+        if [ "${__count}" -eq "${__index}" ]; then
+            eval "${__outvar}=\"\${__item}\""
+            break
+        fi
+        __count=$((__count+1))
+    done
+}
+
+STRING_ITEM_COUNT()
+{
+    local _SPACE_NAME="STRING_ITEM_COUNT"
+
+    local __s="${1}"
+    shift
+
+    local __outvar="${1}"
+    shift
+
+    local __item=
+    local __count=0
+    for __item in ${__s}; do
+        __count=$((__count+1))
+    done
+    eval "${__outvar}=\"\${__count}\""
+}
+
 STRING_REPEAT()
 {
     local _SPACE_NAME="STRING_REPEAT"
@@ -954,60 +1136,6 @@ _QUOTE_ARG()
 
     # Now lift the whole argument.
     STRING_ESCAPE "${argname}"
-}
-
-STRING_ITEM_INDEXOF()
-{
-    local _SPACE_NAME="STRING_ITEM_INDEXOF"
-
-    local __s="${1}"
-    shift
-
-    local __item="${1}"
-    shift
-
-    local __outvar="${1-}"
-    shift $(( $# > 0 ? 1 : 0 ))
-
-    local __item2=
-    local __count=0
-    for __item2 in ${__s}; do
-        if [ "${__item}" = "${__item2}" ]; then
-            if [ -n "${__outvar}" ]; then
-                eval "${__outvar}=\"\${__count}\""
-            fi
-            return 0
-        fi
-        __count=$((__count+1))
-    done
-    if [ -n "${__outvar}" ]; then
-        eval "${__outvar}=\"-1\""
-    fi
-    return 1
-}
-
-STRING_ITEM_GET()
-{
-    local _SPACE_NAME="STRING_ITEM_GET"
-
-    local __s="${1}"
-    shift
-
-    local __index="${1}"
-    shift
-
-    local __outvar="${1}"
-    shift
-
-    local __item=
-    local __count=0
-    for __item in ${__s}; do
-        if [ "${__count}" -eq "${__index}" ]; then
-            eval "${__outvar}=\"\${__item}\""
-            break
-        fi
-        __count=$((__count+1))
-    done
 }
 
 _GET_CONTAINER_NR()
@@ -1408,42 +1536,6 @@ _COMPILE_CPUMEM()
 {
     local _SPACE_NAME="_COMPILE_CPUMEM"
     :
-}
-
-STRING_SUBST()
-{
-    local _SPACE_NAME="STRING_SUBST"
-
-    local __varname="${1}"
-    local __rstring=
-    eval "__rstring=\"\${$1}\""
-    shift
-
-    local __subst="${1}"
-    shift
-
-    local __replace="${1}"
-    shift
-
-    local __global="${1:-0}"
-    shift $(( $# > 0 ? 1 : 0 ))
-
-    local __lstring=
-    local __string=""
-    while true; do
-        __lstring="${__rstring%%${__subst}*}"
-        if [ "${__lstring}" = "${__rstring}" ]; then
-            __string="${__string}${__rstring}"
-            break
-        fi
-        __string="${__string}${__lstring}${__replace}"
-        __rstring="${__rstring#*${__subst}}"
-        if [ "${__global}" -ne 1 ]; then
-            __string="${__string}${__rstring}"
-            break
-        fi
-    done
-    eval "${__varname}=\"\${__string}\""
 }
 
 _GET_CONTAINER_VAR()
@@ -2223,24 +2315,6 @@ _COMPILE_RESTART()
     fi
 }
 
-STRING_ITEM_COUNT()
-{
-    local _SPACE_NAME="STRING_ITEM_COUNT"
-
-    local __s="${1}"
-    shift
-
-    local __outvar="${1}"
-    shift
-
-    local __item=
-    local __count=0
-    for __item in ${__s}; do
-        __count=$((__count+1))
-    done
-    eval "${__outvar}=\"\${__count}\""
-}
-
 YAML_PARSE_IMPL()
 {
     local _SPACE_NAME="YAML_PARSE_IMPL"
@@ -2991,7 +3065,7 @@ main()
     if [ "${_status}" -ne "${SPACE_ASSERT_EXIT}" ]; then
         if [ "${SPACE_MUTE_EXIT_MESSAGE}" != "1" ] && [ "${SPACE_LOG_LEVEL}" -ge 1 ]; then
             [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ -t 2 ] && printf "\033[31m" >&2
-            printf "%s\n" "[ERROR] Script exited with status $_status for node /cmdline/" >&2
+            printf "%s\n" "[ERROR] Script exited with status $_status for node /_cmdline/" >&2
             [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ -t 2 ] && printf "\033[0m" >&2
         fi
         if [ "${SPACE_MUTE_EXIT}" != 1 ]; then
@@ -2999,7 +3073,7 @@ main()
         fi
     elif [ "${SPACE_MUTE_EXIT_MESSAGE}" != "1" ] && [ "${SPACE_LOG_LEVEL}" -ge 5 ]; then
         [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ 5 -eq 3 ] && [ -t 2 ] && printf "\033[32m" >&2
-        printf "%s\n" "[DEBUG] Script exited with success (status $_status) for node /cmdline/" >&2
+        printf "%s\n" "[DEBUG] Script exited with success (status $_status) for node /_cmdline/" >&2
         [ "${SPACE_LOG_ENABLE_COLORS:-1}" = "1" ] && [ 5 -eq 3 ] && [ -t 2 ] && printf "\033[0m" >&2
         : # Important to reset status here.
     fi
