Add readiness/liveness probes Update startup probe

diff --git a/release/podman-runtime b/release/podman-runtime
--- a/release/podman-runtime
+++ b/release/podman-runtime
@@ -339,7 +339,7 @@ _RELOAD_CONFIG()
 
     local config=
     local containersdone=""
-    for config in ${configs}; do
+    for config in "$@"; do
         local container=
         local container_nr=
         for container_nr in $(seq 1 "${POD_CONTAINER_COUNT}"); do
@@ -557,8 +557,6 @@ _LOGS()
             columns="${columns}${columns:+ }\\5"
             sed "s/\\([^ ]\+\\) \\([^ ]\\+\\) \\([^ ]\\+\\) \\([^ ]\\+\\) \\(.*\\)/${columns}/"
         }
-
-    printf "%s\\n" "${files}"
 }
 
 _STOP()
@@ -678,13 +676,59 @@ _SHOW_STATUS()
 _READINESS_PROBE()
 {
     local _SPACE_NAME="_READINESS_PROBE"
-    return 0
+
+    local container_nr=
+    for container_nr in $(seq 1 "${POD_CONTAINER_COUNT}"); do
+        local container=
+        _GET_CONTAINER_VAR "${container_nr}" "NAME" "container"
+        local probe=
+        _GET_CONTAINER_VAR "${container_nr}" "READINESSPROBE" "probe"
+        local timeout=
+        _GET_CONTAINER_VAR "${container_nr}" "READINESSTIMEOUT" "timeout"
+        if [ -n "${probe}" ]; then
+            local containerstatus="$(_CONTAINER_STATUS "${container}")"
+            if [ "${containerstatus}" != "running" ]; then
+                PRINT "Probe for container ${container} failed because container is not running" "debug" 0
+                return 1
+            fi
+            local now=$(date +%s)
+            local expire="$((now + timeout))"
+            if ! _RUN_PROBE "${container}" "${probe}" "${expire}"; then
+                # Probe failed
+                PRINT "Probe for container ${container} failed" "debug" 0
+                return 1
+            fi
+        fi
+    done
 }
 
 _LIVENESS_PROBE()
 {
     local _SPACE_NAME="_LIVENESS_PROBE"
-    return 0
+
+    local container_nr=
+    for container_nr in $(seq 1 "${POD_CONTAINER_COUNT}"); do
+        local container=
+        _GET_CONTAINER_VAR "${container_nr}" "NAME" "container"
+        local probe=
+        _GET_CONTAINER_VAR "${container_nr}" "LIVENESSPROBE" "probe"
+        local timeout=
+        _GET_CONTAINER_VAR "${container_nr}" "LIVENESSTIMEOUT" "timeout"
+        if [ -n "${probe}" ]; then
+            local containerstatus="$(_CONTAINER_STATUS "${container}")"
+            if [ "${containerstatus}" != "running" ]; then
+                PRINT "Liveness probe for container ${container} is skipped because container is not running" "debug" 0
+                continue
+            fi
+            local now=$(date +%s)
+            local expire="$((now + timeout))"
+            if ! _RUN_PROBE "${container}" "${probe}" "${expire}"; then
+                # Probe failed
+                PRINT "Liveness probe for container ${container} failed. Stopping container" "debug" 0
+                _CONTAINER_STOP "${container}"
+            fi
+        fi
+    done
 }
 
 _RAMDISK_CONFIG()
@@ -710,6 +754,14 @@ _CHECK_PODMAN()
     local minor="${ver%[.]*}"
     minor="${minor#*[.]}"
     local patch="${ver##*[.]}"
+
+    if [ "${ver}" = "1.8.0" ]; then
+        PRINT "Podman 1.8.0 is not supported" "error" 0
+        return 1
+    fi
+
+    return 0
+    # Disabled for now since CentOS currently is on podman 1.6.4
 
     if [ "${major}" -gt 1 ]; then
         return 0
@@ -1089,7 +1141,13 @@ _CYCLE_CONTAINER()
     shift
 
     _RM_CONTAINER "${container}"
-    _RUN_CONTAINER "${container}" "${container_nr}"
+    if ! _RUN_CONTAINER "${container}" "${container_nr}"; then
+        if _CONTAINER_EXISTS "${container}"; then
+            # Kill it first, because it is quicker
+            _CONTAINER_KILL "${container}"
+            _RM_CONTAINER "${container}"
+        fi
+    fi
 }
 
 _CONTAINER_STATUS()
@@ -1351,6 +1409,57 @@ _OUTPUT_CONTAINER_INFO()
     fi
 }
 
+_RUN_PROBE()
+{
+    local _SPACE_NAME="_RUN_PROBE"
+
+    local container="${1}"
+    shift
+
+    local command="${1}"
+    shift
+
+    local timeout="${1}"
+    shift
+
+    PRINT "podman exec ${container} ${command}" "debug" 0
+
+    eval "podman exec ${container} ${command} >/dev/null 2>&1"&
+    local pid="$!"
+    while true; do
+        if ! kill -0 "${pid}" 2>/dev/null; then
+            # Process ended, get exit code.
+            if wait "${pid}"; then
+                # exit code 0, success.
+                return 0
+            else
+                # Probe did not succeed.
+                return 1
+            fi
+        fi
+
+        # Process still alive, check overall timeout.
+        now=$(date +%s)
+        if [ "${now}" -ge "${timeout}" ]; then
+            # Probe did not succeed.
+            # Kill process.
+            kill -9 "${pid}"
+            return 1
+        fi
+
+        sleep 1
+    done
+}
+
+_CONTAINER_STOP()
+{
+    local _SPACE_NAME="_CONTAINER_STOP"
+
+    local container="${1}"
+
+    podman stop "${container}" >/dev/null
+}
+
 STRING_SUBSTR()
 {
     local _SPACE_NAME="STRING_SUBSTR"
@@ -1574,18 +1683,18 @@ _RUN_CONTAINER()
     done
 
     # Wait for startup probe on container
-    local wait=
-    _GET_CONTAINER_VAR "${container_nr}" "WAIT" "wait"
-    local waittimeout=
-    _GET_CONTAINER_VAR "${container_nr}" "WAITTIMEOUT" "waittimeout"
-    waittimeout="${waittimeout:-120}"
-    if [ -n "${wait}" ]; then
+    local startupProbe=
+    _GET_CONTAINER_VAR "${container_nr}" "STARTUPPROBE" "startupProbe"
+    local startupTimeout=
+    _GET_CONTAINER_VAR "${container_nr}" "STARTUPTIMEOUT" "startupTimeout"
+    startupTimeout="${startupTimeout:-120}"
+    if [ -n "${startupProbe}" ]; then
         local now=$(date +%s)
-        local timeout=$((now + waittimeout))
+        local timeout=$((now + startupTimeout))
         PRINT "Container ${container} waiting to startup" "info" 0
         while true; do
             local containerstatus="$(_CONTAINER_STATUS "${container}")"
-            if [ "${wait}" = "exit" ]; then
+            if [ "${startupProbe}" = "exit" ]; then
                 if [ "${containerstatus}" != "running" ]; then
                     local exitcode="$(_CONTAINER_EXITCODE "${container}")"
                     if [ "${exitcode}" -eq 0 ]; then
@@ -1596,9 +1705,6 @@ _RUN_CONTAINER()
                         return 1
                     fi
                 fi
-            elif [ "${wait%%:*}" = "tcp" ]; then
-                # TODO: run the startup tcp probe
-                return 1
             else
                 # Run shell command in container
                 if [ "${containerstatus}" != "running" ]; then
@@ -1607,34 +1713,15 @@ _RUN_CONTAINER()
                 fi
 
                 # Run this in subprocess and kill it if it takes too long.
-                eval "podman exec ${container} ${wait} >/dev/null 2>&1"&
-                local pid=$!
-                while true; do
-                    sleep 1
-                    if ! kill -0 "${pid}" 2>/dev/null; then
-                        # Process ended
-                        if wait "${pid}"; then
-                            # Break out 2 because we are done with our checks.
-                            break 2
-                        else
-                            # Break out of this loop so command could run again.
-                            break
-                        fi
-                    fi
-
-                    # Process still alive, check overall timeout.
-                    now=$(date +%s)
-                    if [ "${now}" -ge "${timeout}" ]; then
-                        # Kill process and break this loop so the second timeout check can trigger also.
-                        kill -9 "${pid}"
-                        break
-                    fi
-                done
+                if _RUN_PROBE "${container}" "${startupProbe}" "${timeout}"; then
+                    # Probe succeded
+                    break
+                fi
             fi
 
             now=$(date +%s)
             if [ "${now}" -ge "${timeout}" ]; then
-                # The container did not start up properly, it will be up to the caller to decide if to destroy it or not.
+                 # The container did not start up properly, it will be up to the caller to decide if to destroy it or not.
                 PRINT "Container ${container} timeouted waiting to exit/become ready" "error" 0
                 return 1
             fi
@@ -1647,7 +1734,7 @@ _RUN_CONTAINER()
 
     # Fire the signalling to other containers that this container is started (which could mean started and successfully exited).
     local signals=
-    _GET_CONTAINER_VAR "${container_nr}" "SENDSIGNALS" "signals"
+    _GET_CONTAINER_VAR "${container_nr}" "STARTUPSIGNAL" "signals"
     if [ -n "${signals}" ]; then
         local container_nr=
         local container=
@@ -1704,13 +1791,13 @@ _CONTAINER_FINISHEDAT()
     printf "%s\\n" "${ts}"
 }
 
-_CONTAINER_STOP()
+_CONTAINER_KILL()
 {
-    local _SPACE_NAME="_CONTAINER_STOP"
+    local _SPACE_NAME="_CONTAINER_KILL"
 
     local container="${1}"
 
-    podman stop "${container}"
+    podman kill "${container}"
 }
 
 STRING_IS_ALL()
@@ -1731,15 +1818,6 @@ STRING_IS_ALL()
         *)
             ;;
     esac
-}
-
-_CONTAINER_KILL()
-{
-    local _SPACE_NAME="_CONTAINER_KILL"
-
-    local container="${1}"
-
-    podman kill "${container}"
 }
 
 STRING_REPEAT()
